version: "3.8"

services:
  #PHP
  php:
    container_name: php_c
    build: .
    user: nonroot
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  #MYSQL
  mysql:
    container_name: mysql_c
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db_password
      MYSQL_DATABASE: your_db
  #NODE
  node:
    container_name: node_c
    user: node
    image: node:lts
    command: tail -f /dev/null
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - "NODE_ENV=development"


